import Airtable from 'airtable';
import Head from 'next/head';
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const airtable = new Airtable({
    apiKey: process.env.NEXT_PUBLIC_API_KEY,
    view: 'Grid View',
  });

  const records = await airtable
    .base(process.env.NEXT_PUBLIC_BASE_ID)('AI')
    .select({
      fields: ['Name'],
      view: 'Grid View',
    })
    .all();

  const products = records.map((sig) => {
    return {
      name: sig.get('Name'),
      type: sig.get('Name'),
    };
  });

  return {
    props: {
      products,
    },
    revalidate: 30,
  };
}

function Product({ name }) {
  return (      
         <div className="card">
             <h2>{name}</h2>
             <i>Content Description Goes Here</i>
             <p>Actual Content Goes Here </p>
         </div>
  );
}

export default function Web({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Turner Fenton Secondary School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container" style={{ padding: '50px 0 100px 0' }}>

          <h1>Machine Learning / AI Track</h1>
          <p>A curated list of resources to supercharge your skills in AI:</p><br/><br/>
        

<div className="grid">

        {products.map((sig) => (
          <Product
            key={sig.name}
            name={sig.name}
          />    
        ))}
        </div>

        
      </div>
    </div>
  )
}

